let locations = [];let routes = [];let graph = {};let mode = "visitor";let currentPath = [];let view = { scale: 1, x: 0, y: 0 };let dragging = false;let dragStart = null;const byId = (id) => document.getElementById(id);const MAP_W = 4200;const MAP_H = 1187;
async function init(){locations=await fetch("data/locations.json").then(r=>r.json());routes=await fetch("data/routes.json").then(r=>r.json());buildGraph();populateSelects();drawZones();drawNetwork();drawNodes();bindUI();setModeDefaults();resetView();}
function bindUI(){byId("routeBtn").addEventListener("click",generateRoute);byId("zoomIn").addEventListener("click",()=>zoomAt(1.2,frameCenter()));byId("zoomOut").addEventListener("click",()=>zoomAt(1/1.2,frameCenter()));byId("resetView").addEventListener("click",resetView);byId("fitRoute").addEventListener("click",fitCurrentRoute);byId("labelToggle").addEventListener("change",e=>byId("overlay").classList.toggle("labels-off",!e.target.checked));byId("networkToggle").addEventListener("change",e=>byId("overlay").classList.toggle("network-off",!e.target.checked));document.querySelectorAll(".mode").forEach(btn=>{btn.addEventListener("click",()=>{document.querySelectorAll(".mode").forEach(b=>b.classList.remove("active"));btn.classList.add("active");mode=btn.dataset.mode;setModeDefaults();});});document.querySelectorAll(".quick-actions button").forEach(btn=>{btn.addEventListener("click",()=>runPreset(btn.dataset.preset));});byId("searchBox").addEventListener("keydown",e=>{if(e.key==="Enter")selectSearch();});byId("searchBox").addEventListener("input",()=>softSearch());const frame=byId("mapFrame");frame.addEventListener("wheel",e=>{e.preventDefault();const delta=e.deltaY<0?1.14:1/1.14;zoomAt(delta,{x:e.offsetX,y:e.offsetY});},{passive:false});frame.addEventListener("pointerdown",e=>{dragging=true;frame.classList.add("dragging");frame.setPointerCapture(e.pointerId);dragStart={px:e.clientX,py:e.clientY,x:view.x,y:view.y};});frame.addEventListener("pointermove",e=>{if(!dragging)return;view.x=dragStart.x+(e.clientX-dragStart.px);view.y=dragStart.y+(e.clientY-dragStart.py);applyTransform();});frame.addEventListener("pointerup",()=>{dragging=false;frame.classList.remove("dragging");});}
function buildGraph(){graph={};locations.forEach(l=>graph[l.id]=[]);routes.forEach(([a,b,w])=>{graph[a].push({id:b,weight:w});graph[b].push({id:a,weight:w});});}
function loc(id){return locations.find(l=>l.id===id);}
function populateSelects(){const start=byId("startSelect");const end=byId("endSelect");locations.forEach(l=>{start.add(new Option(l.name,l.id));end.add(new Option(l.name,l.id));});}
function setModeDefaults(){if(mode==="visitor"){byId("startSelect").value="main_guard_house";byId("endSelect").value="visitor_badging";byId("subtitle").textContent="Visitor-safe guided routing";}else if(mode==="employee"){byId("startSelect").value="main_guard_house";byId("endSelect").value="formation";byId("subtitle").textContent="Employee pedestrian movement";}else{byId("startSelect").value="center_junction";byId("endSelect").value="muster_center";byId("subtitle").textContent="Emergency reference routing";}generateRoute();}
function runPreset(preset){if(preset==="visitor_training"){byId("startSelect").value="main_guard_house";byId("endSelect").value="training_center";}if(preset==="main_formation"){byId("startSelect").value="main_guard_house";byId("endSelect").value="formation";}if(preset==="module_area"){byId("startSelect").value="module_guard_house";byId("endSelect").value="module_area";}generateRoute();}
function drawZones(){const layer=byId("zoneLayer");layer.innerHTML="";[{x:520,y:270,w:650,h:450},{x:1450,y:350,w:950,h:310},{x:2240,y:440,w:700,h:430},{x:3100,y:320,w:760,h:470}].forEach(z=>{const r=document.createElementNS("http://www.w3.org/2000/svg","rect");r.setAttribute("x",z.x);r.setAttribute("y",z.y);r.setAttribute("width",z.w);r.setAttribute("height",z.h);r.setAttribute("rx",20);r.setAttribute("class","zone");layer.appendChild(r);});}
function drawNetwork(){const layer=byId("networkLayer");layer.innerHTML="";routes.forEach(([a,b])=>{const A=loc(a),B=loc(b);const line=document.createElementNS("http://www.w3.org/2000/svg","line");line.setAttribute("x1",A.x);line.setAttribute("y1",A.y);line.setAttribute("x2",B.x);line.setAttribute("y2",B.y);line.setAttribute("class","network");layer.appendChild(line);});}
function drawNodes(){const layer=byId("nodeLayer");layer.innerHTML="";locations.forEach(l=>{const g=document.createElementNS("http://www.w3.org/2000/svg","g");g.setAttribute("class",`node ${l.type}`);g.setAttribute("transform",`translate(${l.x},${l.y})`);g.dataset.id=l.id;const ring=document.createElementNS("http://www.w3.org/2000/svg","circle");ring.setAttribute("class","ring");ring.setAttribute("r","0");const c=document.createElementNS("http://www.w3.org/2000/svg","circle");c.setAttribute("class","dot");c.setAttribute("r","22");const label=document.createElementNS("http://www.w3.org/2000/svg","text");label.setAttribute("x","34");label.setAttribute("y","-24");label.textContent=l.shortName||l.name;g.appendChild(ring);g.appendChild(c);g.appendChild(label);g.addEventListener("click",()=>{byId("endSelect").value=l.id;showDestination(l.id);generateRoute();});layer.appendChild(g);});}
function dijkstra(start,end){const dist={},prev={},q=new Set(Object.keys(graph));Object.keys(graph).forEach(k=>dist[k]=Infinity);dist[start]=0;while(q.size){let u=[...q].sort((a,b)=>dist[a]-dist[b])[0];q.delete(u);if(u===end)break;for(const n of graph[u]){const alt=dist[u]+n.weight;if(alt<dist[n.id]){dist[n.id]=alt;prev[n.id]=u;}}}const path=[];let u=end;while(u){path.unshift(u);u=prev[u];}return{path,distance:dist[end]};}
function generateRoute(){const start=byId("startSelect").value;const end=byId("endSelect").value;if(!start||!end||start===end)return;const result=dijkstra(start,end);currentPath=result.path;drawRoute(result.path);updateRouteCard(result);showDestination(end);fitCurrentRoute();}
function drawRoute(path){const layer=byId("routeLayer");layer.innerHTML="";const points=path.map(id=>`${loc(id).x},${loc(id).y}`).join(" ");const pl=document.createElementNS("http://www.w3.org/2000/svg","polyline");pl.setAttribute("points",points);pl.setAttribute("class","route");pl.setAttribute("marker-end","url(#arrow)");layer.appendChild(pl);document.querySelectorAll(".node").forEach(n=>n.classList.remove("selected"));path.forEach(id=>{const node=document.querySelector(`.node[data-id="${id}"]`);if(node)node.classList.add("selected");});}
function updateRouteCard(result){const feet=Math.round(result.distance*1.7);const mins=Math.max(1,Math.round(feet/250));byId("routeStatus").textContent="AUTHORIZED";byId("distanceMetric").textContent=`${feet} ft`;byId("timeMetric").textContent=`${mins} min`;const steps=byId("steps");steps.innerHTML="";result.path.forEach((id,i)=>{const l=loc(id);const div=document.createElement("div");div.className="step";div.innerHTML=`<strong>${i+1}. ${l.name}</strong><br><span>${l.description}</span>`;steps.appendChild(div);});}
function showDestination(id){const l=loc(id);byId("drawerTitle").textContent=l.name;byId("drawerDesc").textContent=l.description;byId("drawerAccess").textContent=l.access;}
function softSearch(){const q=byId("searchBox").value.toLowerCase().trim();if(!q)return;const hit=locations.find(l=>`${l.name} ${l.shortName} ${l.category}`.toLowerCase().includes(q));if(hit)showDestination(hit.id);}
function selectSearch(){const q=byId("searchBox").value.toLowerCase().trim();const hit=locations.find(l=>`${l.name} ${l.shortName} ${l.category}`.toLowerCase().includes(q));if(hit){byId("endSelect").value=hit.id;generateRoute();}}
function applyTransform(){byId("mapContent").style.transform=`translate(${view.x}px, ${view.y}px) scale(${view.scale})`;}
function frameCenter(){const f=byId("mapFrame");return{x:f.clientWidth/2,y:f.clientHeight/2};}
function zoomAt(factor,pt){const old=view.scale;const next=Math.max(1,Math.min(5,old*factor));const mapX=(pt.x-view.x)/old;const mapY=(pt.y-view.y)/old;view.scale=next;view.x=pt.x-mapX*next;view.y=pt.y-mapY*next;applyTransform();}
function resetView(){view={scale:1,x:0,y:0};applyTransform();}
function fitCurrentRoute(){if(!currentPath.length)return;const frame=byId("mapFrame");const xs=currentPath.map(id=>loc(id).x);const ys=currentPath.map(id=>loc(id).y);const minX=Math.min(...xs)-300,maxX=Math.max(...xs)+300;const minY=Math.min(...ys)-180,maxY=Math.max(...ys)+180;const sx=frame.clientWidth/(maxX-minX);const sy=frame.clientHeight/(maxY-minY);const scale=Math.max(1,Math.min(3.2,Math.min(sx,sy)));view.scale=scale;view.x=-(minX/MAP_W)*frame.clientWidth*scale+(frame.clientWidth-((maxX-minX)/MAP_W)*frame.clientWidth*scale)/2;view.y=-(minY/MAP_H)*frame.clientHeight*scale+(frame.clientHeight-((maxY-minY)/MAP_H)*frame.clientHeight*scale)/2;applyTransform();}
init();