let locations=[],routes=[],graph={},mode="visitor",lastPath=[],view={scale:1,x:0,y:0},dragging=false,dragStart=null;
const byId=id=>document.getElementById(id); const loc=id=>locations.find(l=>l.id===id);
async function init(){locations=await fetch("data/locations.json").then(r=>r.json());routes=await fetch("data/routes.json").then(r=>r.json());buildGraph();populateSelects();drawNetwork();drawNodes();wireEvents();resetView();setModeDefaults();}
function wireEvents(){byId("routeBtn").addEventListener("click",generateRoute);byId("zoomIn").addEventListener("click",()=>zoomAt(1.2));byId("zoomOut").addEventListener("click",()=>zoomAt(.83));byId("resetView").addEventListener("click",resetView);byId("fitRoute").addEventListener("click",fitRoute);byId("labelsToggle").addEventListener("change",e=>byId("overlay").classList.toggle("hide-labels",!e.target.checked));byId("networkToggle").addEventListener("change",e=>byId("overlay").classList.toggle("hide-network",!e.target.checked));document.querySelectorAll(".mode").forEach(btn=>btn.addEventListener("click",()=>{document.querySelectorAll(".mode").forEach(b=>b.classList.remove("active"));btn.classList.add("active");mode=btn.dataset.mode;setModeDefaults();}));document.querySelectorAll(".preset").forEach(btn=>btn.addEventListener("click",()=>{byId("startSelect").value=btn.dataset.start;byId("endSelect").value=btn.dataset.end;generateRoute();fitRoute();}));byId("searchBox").addEventListener("input",e=>{const q=e.target.value.toLowerCase().trim();const f=locations.find(l=>(`${l.name} ${l.label||''} ${l.category}`).toLowerCase().includes(q));if(f&&q.length>1){byId("endSelect").value=f.id;showDestination(f.id)}});const frame=byId("mapFrame");frame.addEventListener("wheel",e=>{e.preventDefault();zoomAt(e.deltaY<0?1.12:.89)}, {passive:false});frame.addEventListener("mousedown",e=>{dragging=true;dragStart={x:e.clientX,y:e.clientY,vx:view.x,vy:view.y};frame.classList.add("dragging")});window.addEventListener("mousemove",e=>{if(!dragging)return;view.x=dragStart.vx+(e.clientX-dragStart.x);view.y=dragStart.vy+(e.clientY-dragStart.y);applyView()});window.addEventListener("mouseup",()=>{dragging=false;frame.classList.remove("dragging")});}
function buildGraph(){graph={};locations.forEach(l=>graph[l.id]=[]);routes.forEach(([a,b,w])=>{graph[a].push({id:b,weight:w});graph[b].push({id:a,weight:w})})}
function populateSelects(){const s=byId("startSelect"),e=byId("endSelect");s.innerHTML="";e.innerHTML="";locations.forEach(l=>{s.add(new Option(l.name,l.id));e.add(new Option(l.name,l.id))})}
function setModeDefaults(){if(mode==="visitor"){byId("startSelect").value="main_guard_house";byId("endSelect").value="visitor_badging";byId("subtitle").textContent="Visitor-safe guided routing"}else if(mode==="employee"){byId("startSelect").value="main_guard_house";byId("endSelect").value="formation";byId("subtitle").textContent="Employee pedestrian movement"}else{byId("startSelect").value="center_junction";byId("endSelect").value="muster_center";byId("subtitle").textContent="Emergency reference routing"}generateRoute()}
function drawNetwork(){const layer=byId("networkLayer");layer.innerHTML="";routes.forEach(([a,b])=>{const A=loc(a),B=loc(b);const line=document.createElementNS("http://www.w3.org/2000/svg","line");line.setAttribute("x1",A.x);line.setAttribute("y1",A.y);line.setAttribute("x2",B.x);line.setAttribute("y2",B.y);line.setAttribute("class","network");layer.appendChild(line)})}
function drawNodes(){const layer=byId("nodeLayer");layer.innerHTML="";locations.forEach(l=>{const g=document.createElementNS("http://www.w3.org/2000/svg","g");g.setAttribute("class",`node ${l.type}`);g.setAttribute("transform",`translate(${l.x},${l.y})`);g.dataset.id=l.id;const ring=document.createElementNS("http://www.w3.org/2000/svg","circle");ring.setAttribute("class","ring");ring.setAttribute("r","0");const c=document.createElementNS("http://www.w3.org/2000/svg","circle");c.setAttribute("class","dot");c.setAttribute("r","6.5");const label=document.createElementNS("http://www.w3.org/2000/svg","text");label.setAttribute("x","10");label.setAttribute("y","-8");label.textContent=l.label||l.name;g.appendChild(ring);g.appendChild(c);g.appendChild(label);g.addEventListener("click",()=>{showDestination(l.id);byId("endSelect").value=l.id});layer.appendChild(g)})}
function dijkstra(start,end){const dist={},prev={},q=new Set(Object.keys(graph));Object.keys(graph).forEach(k=>dist[k]=Infinity);dist[start]=0;while(q.size){let u=[...q].sort((a,b)=>dist[a]-dist[b])[0];q.delete(u);if(u===end)break;for(const n of graph[u]){const alt=dist[u]+n.weight;if(alt<dist[n.id]){dist[n.id]=alt;prev[n.id]=u}}}const path=[];let u=end;while(u){path.unshift(u);u=prev[u]}return{path,distance:dist[end]}}
function generateRoute(){const start=byId("startSelect").value,end=byId("endSelect").value;if(!start||!end||start===end)return;const result=dijkstra(start,end);lastPath=result.path;drawRoute(result.path);updateRouteCard(result);showDestination(end)}
function drawRoute(path){const layer=byId("routeLayer");layer.innerHTML="";const points=path.map(id=>`${loc(id).x},${loc(id).y}`).join(" ");const pl=document.createElementNS("http://www.w3.org/2000/svg","polyline");pl.setAttribute("points",points);pl.setAttribute("class","route");pl.setAttribute("marker-end","url(#arrow)");layer.appendChild(pl);document.querySelectorAll(".node").forEach(n=>n.classList.remove("selected"));path.forEach(id=>{const node=document.querySelector(`.node[data-id="${id}"]`);if(node)node.classList.add("selected")})}
function updateRouteCard(result){const feet=Math.round(result.distance*1.7),mins=Math.max(1,Math.round(feet/250));byId("routeStatus").textContent="AUTHORIZED";byId("distanceMetric").textContent=`${feet} ft`;byId("timeMetric").textContent=`${mins} min`;const steps=byId("steps");steps.innerHTML="";result.path.forEach((id,i)=>{const l=loc(id),div=document.createElement("div");div.className="step";div.innerHTML=`<strong>${i+1}. ${l.name}</strong><br><span>${l.description}</span>`;steps.appendChild(div)})}
function showDestination(id){const l=loc(id);byId("drawerTitle").textContent=l.name;byId("drawerDesc").textContent=l.description;byId("drawerAccess").textContent=l.access}
function applyView(){byId("mapStage").style.transform=`translate(calc(-50% + ${view.x}px), calc(-50% + ${view.y}px)) scale(${view.scale})`}
function resetView(){const f=byId("mapFrame");view.scale=Math.min(f.clientWidth/1024,f.clientHeight/768)*.96;view.x=0;view.y=0;applyView()}
function zoomAt(factor){view.scale=Math.max(.35,Math.min(5,view.scale*factor));applyView()}
function fitRoute(){if(!lastPath.length)return;const f=byId("mapFrame"),pts=lastPath.map(id=>loc(id));const minX=Math.min(...pts.map(p=>p.x)),maxX=Math.max(...pts.map(p=>p.x)),minY=Math.min(...pts.map(p=>p.y)),maxY=Math.max(...pts.map(p=>p.y));const pad=120,routeW=maxX-minX+pad*2,routeH=maxY-minY+pad*2;view.scale=Math.min(f.clientWidth/routeW,f.clientHeight/routeH,2.7);const cx=(minX+maxX)/2,cy=(minY+maxY)/2;view.x=(512-cx)*view.scale;view.y=(384-cy)*view.scale;applyView()}
window.addEventListener("resize",resetView);init();