let destinations=[],routes=[],graph={},lastPath=[],mode="visitor";let view={scale:1,x:0,y:0};let dragging=false,dragStart=null;const MAP_W=12096,MAP_H=3460;const $=id=>document.getElementById(id);const loc=id=>destinations.find(d=>d.id===id);
async function init(){destinations=await fetch("data/destinations.json").then(r=>r.json());routes=await fetch("data/routes.json").then(r=>r.json());buildGraph();sizeStage();populate();drawNetwork();drawNodes();wire();resetView();setMode("visitor");updateClock();setInterval(updateClock,30000);}
function sizeStage(){const st=$("mapStage"),img=$("plantMap"),svg=$("overlay");st.style.width=MAP_W+"px";st.style.height=MAP_H+"px";img.style.width=MAP_W+"px";img.style.height=MAP_H+"px";svg.style.width=MAP_W+"px";svg.style.height=MAP_H+"px";}
function buildGraph(){destinations.forEach(d=>graph[d.id]=[]);routes.forEach(([a,b,w])=>{graph[a].push({id:b,weight:w});graph[b].push({id:a,weight:w})})}
function populate(){const s=$("startSelect"),e=$("endSelect");destinations.forEach(d=>{s.add(new Option(d.name,d.id));e.add(new Option(d.name,d.id));})}
function wire(){$("routeBtn").onclick=generateRoute;$("zoomIn").onclick=()=>zoom(1.2);$("zoomOut").onclick=()=>zoom(.83);$("resetView").onclick=resetView;$("centerView").onclick=resetView;$("fitRoute").onclick=fitRoute;$("searchFocus").onclick=()=>$("searchBox").focus();$("fullscreenBtn").onclick=()=>document.documentElement.requestFullscreen?.();$("layersBtn").onclick=()=>$("layersModal").classList.add("show");$("legendBtn").onclick=()=>document.querySelector(".legend-box").classList.toggle("hidden");$("closeModal").onclick=()=>$("layersModal").classList.remove("show");
document.querySelectorAll(".mode").forEach(b=>b.onclick=()=>setMode(b.dataset.mode));document.querySelectorAll(".preset").forEach(b=>b.onclick=()=>{$("startSelect").value=b.dataset.start;$("endSelect").value=b.dataset.end;generateRoute();fitRoute();});
$("labelsToggle").onchange=e=>toggleLabels(e.target.checked);$("networkToggle").onchange=e=>toggleNetwork(e.target.checked);$("modalLabels").onchange=e=>{$("labelsToggle").checked=e.target.checked;toggleLabels(e.target.checked)};$("modalNetwork").onchange=e=>{$("networkToggle").checked=e.target.checked;toggleNetwork(e.target.checked)};
$("searchBox").oninput=e=>{const q=e.target.value.toLowerCase().trim();const d=destinations.find(x=>(x.name+" "+x.label+" "+x.category).toLowerCase().includes(q));if(d&&q.length>1){$("endSelect").value=d.id;showDestination(d.id);}};
const f=$("mapFrame");f.onwheel=e=>{e.preventDefault();zoom(e.deltaY<0?1.12:.89)};f.onmousedown=e=>{dragging=true;dragStart={x:e.clientX,y:e.clientY,vx:view.x,vy:view.y};f.classList.add("dragging")};window.onmousemove=e=>{if(!dragging)return;view.x=dragStart.vx+e.clientX-dragStart.x;view.y=dragStart.vy+e.clientY-dragStart.y;applyView()};window.onmouseup=()=>{dragging=false;f.classList.remove("dragging")};window.onresize=resetView;}
function setMode(m){mode=m;document.querySelectorAll(".mode").forEach(b=>b.classList.toggle("active",b.dataset.mode===m));if(m==="visitor"){$("startSelect").value="main_guard_house";$("endSelect").value="visitor_badging";$("subtitle").textContent="Visitor-safe guided routing"}else if(m==="employee"){$("startSelect").value="main_guard_house";$("endSelect").value="formation";$("subtitle").textContent="Employee pedestrian movement"}else{$("startSelect").value="center_junction";$("endSelect").value="muster_center";$("subtitle").textContent="Emergency reference routing"}generateRoute();}
function drawNetwork(){const l=$("networkLayer");l.innerHTML="";routes.forEach(([a,b])=>{const A=loc(a),B=loc(b);const line=document.createElementNS("http://www.w3.org/2000/svg","line");line.setAttribute("x1",A.x);line.setAttribute("y1",A.y);line.setAttribute("x2",B.x);line.setAttribute("y2",B.y);line.setAttribute("class","network");l.appendChild(line)})}
function drawNodes(){const l=$("nodeLayer");l.innerHTML="";destinations.forEach(d=>{const g=document.createElementNS("http://www.w3.org/2000/svg","g");g.setAttribute("class","node "+d.type);g.setAttribute("transform",`translate(${d.x},${d.y})`);g.dataset.id=d.id;g.innerHTML=`<circle class="ring" r="0"></circle><circle class="dot" r="12"></circle><text x="16" y="-12">${d.label}</text>`;g.onclick=()=>{$("endSelect").value=d.id;showDestination(d.id)};l.appendChild(g)})}
function dijkstra(start,end){const dist={},prev={},q=new Set(Object.keys(graph));Object.keys(graph).forEach(k=>dist[k]=Infinity);dist[start]=0;while(q.size){let u=[...q].sort((a,b)=>dist[a]-dist[b])[0];q.delete(u);if(u===end)break;for(const n of graph[u]){const alt=dist[u]+n.weight;if(alt<dist[n.id]){dist[n.id]=alt;prev[n.id]=u}}}const path=[];let u=end;while(u){path.unshift(u);u=prev[u]}return{path,distance:dist[end]}}
function generateRoute(){const start=$("startSelect").value,end=$("endSelect").value;if(!start||!end||start===end)return;const r=dijkstra(start,end);lastPath=r.path;drawRoute(r.path);updateRoute(r);showDestination(end);}
function drawRoute(path){const l=$("routeLayer");l.innerHTML="";const p=path.map(id=>`${loc(id).x},${loc(id).y}`).join(" ");const pl=document.createElementNS("http://www.w3.org/2000/svg","polyline");pl.setAttribute("points",p);pl.setAttribute("class","route");pl.setAttribute("marker-end","url(#arrow)");l.appendChild(pl);document.querySelectorAll(".node").forEach(n=>n.classList.remove("selected"));path.forEach(id=>document.querySelector(`.node[data-id="${id}"]`)?.classList.add("selected"));}
function updateRoute(r){const feet=Math.round(r.distance*1.7),mins=Math.max(1,Math.round(feet/250));$("routeStatus").textContent="AUTHORIZED";$("distanceMetric").textContent=feet+" ft";$("timeMetric").textContent=mins+" min";$("sumDistance").textContent=feet+" ft";$("sumTime").textContent=mins+" min";$("sumStart").textContent=loc(r.path[0]).name;$("sumEnd").textContent=loc(r.path.at(-1)).name;const steps=$("steps");steps.innerHTML="";r.path.forEach((id,i)=>{const d=loc(id),el=document.createElement("div");el.className="step";el.innerHTML=`<b>${i+1}. ${d.name}</b><br>${d.description}`;steps.appendChild(el)});}
function showDestination(id){const d=loc(id);$("drawerTitle").textContent=d.name;$("drawerDesc").textContent=d.description;$("drawerAccess").textContent=d.access;}
function applyView(){$("mapStage").style.transform=`translate(calc(-50% + ${view.x}px), calc(-50% + ${view.y}px)) scale(${view.scale})`}
function resetView(){const f=$("mapFrame");view.scale=Math.min(f.clientWidth/MAP_W,f.clientHeight/MAP_H)*.94;view.x=0;view.y=0;applyView();}
function zoom(f){view.scale=Math.max(.18,Math.min(6,view.scale*f));applyView();}
function fitRoute(){if(!lastPath.length)return;const f=$("mapFrame"),pts=lastPath.map(loc);const minX=Math.min(...pts.map(p=>p.x)),maxX=Math.max(...pts.map(p=>p.x)),minY=Math.min(...pts.map(p=>p.y)),maxY=Math.max(...pts.map(p=>p.y));const pad=180;view.scale=Math.min(f.clientWidth/(maxX-minX+pad*2),f.clientHeight/(maxY-minY+pad*2),2.5);view.x=(MAP_W/2-(minX+maxX)/2)*view.scale;view.y=(MAP_H/2-(minY+maxY)/2)*view.scale;applyView();}
function toggleLabels(show){$("overlay").classList.toggle("hide-labels",!show)}function toggleNetwork(show){$("overlay").classList.toggle("hide-network",!show)}
function updateClock(){$("clock").textContent=new Date().toLocaleTimeString([],{hour:"numeric",minute:"2-digit"})}init();